version: "3.6"

services:
  backend:
    build:
      context: ./Inventario
      dockerfile: Dockerfile
    ports:
      - "8000:80"

  frontend:
    build:
      context: ./Cliente
      dockerfile: Dockerfile
    ports:
      - "4200:4200"
    depends_on: 
      - backend
